name: DSA C++ CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ environment
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Build C++ files
        run: |
          ls -R  # Check the folder structure
          cd graph
          ls     # Check if files are listed here
          g++ -o buildgraph buildgraph.cpp
          ./buildgraph
